<a href="https://colab.research.google.com/github/futurexskill/ml-model-deployment/blob/main/tf_customer_buy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
dataset = pd.read_csv('https://raw.githubusercontent.com/futurexskill/ml-model-deployment/main/storepurchasedata_large.csv')


In [3]:
dataset.describe()

Age        Salary    Purchased
count  1554.000000   1554.000000  1554.000000
mean     44.296010  57042.471042     0.694981
std      17.462458  21209.244800     0.460564
min      18.000000  20000.000000     0.000000
25%      27.000000  46000.000000     0.000000
50%      43.000000  60000.000000     1.000000
75%      62.000000  66000.000000     1.000000
max      69.000000  96000.000000     1.000000

In [4]:
dataset.head()

Age  Salary  Purchased
0   18   20000          0
1   19   22000          0
2   20   24000          0
3   21   28000          0
4   22   60000          1

In [5]:

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =.20,random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(10, activation='relu'),
  tf.keras.layers.Dense(10, activation='relu'),
  tf.keras.layers.Dense(2, activation='softmax')
])

In [9]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [10]:
model.fit(X_train, y_train, epochs=50)


Epoch 1/50
39/39 [==============================] - 0s 1ms/step - loss: 0.6066 - accuracy: 0.7940
Epoch 2/50
39/39 [==============================] - 0s 978us/step - loss: 0.5066 - accuracy: 0.8962
Epoch 3/50
39/39 [==============================] - 0s 997us/step - loss: 0.4019 - accuracy: 0.9509
Epoch 4/50
39/39 [==============================] - 0s 1ms/step - loss: 0.3035 - accuracy: 0.9533
Epoch 5/50
39/39 [==============================] - 0s 1ms/step - loss: 0.2297 - accuracy: 0.9533
Epoch 6/50
39/39 [==============================] - 0s 1ms/step - loss: 0.1818 - accuracy: 0.9541
Epoch 7/50
39/39 [==============================] - 0s 1ms/step - loss: 0.1560 - accuracy: 0.9558
Epoch 8/50
39/39 [==============================] - 0s 1ms/step - loss: 0.1412 - accuracy: 0.9558
Epoch 9/50
39/39 [==============================] - 0s 995us/step - loss: 0.1322 - accuracy: 0.9558
Epoch 10/50
39/39 [==============================] - 0s 987us/step - loss: 0.1267 - accuracy: 0.9549
Epoch 11/50

In [11]:
loss, accuracy =model.evaluate(X_test, y_test)


10/10 [==============================] - 0s 1ms/step - loss: 0.1088 - accuracy: 0.9550


In [12]:
loss

0.1088424026966095

In [13]:
accuracy

0.9549839496612549

In [14]:
model.summary()


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                30        
_________________________________________________________________
dense_1 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 22        
Total params: 162
Trainable params: 162
Non-trainable params: 0
_________________________________________________________________


In [15]:
 prediction1 = model.predict(sc.transform(np.array([[42,50000]])))[:,1]
 prediction1

array([0.64286834], dtype=float32)

In [16]:
predict2 = model.predict(sc.transform(np.array([[20,40000]])))[:,1]
predict2

array([0.00796465], dtype=float32)

In [17]:
model.save('customer_behavior_model/1')


Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
INFO:tensorflow:Assets written to: customer_behavior_model/1/assets


In [18]:
!ls

customer_behavior_model  sample_data


In [19]:
!ls customer_behavior_model  

1


In [20]:
!ls customer_behavior_model/1

assets	saved_model.pb	variables


In [21]:
from tensorflow.keras.models import load_model


In [22]:
cust_model = load_model('customer_behavior_model/1/')

In [23]:
 prediction3 = cust_model.predict(sc.transform(np.array([[42,50000]])))[:,1]
 prediction3

array([0.64286834], dtype=float32)

In [24]:
predict4 = model.predict(sc.transform(np.array([[20,40000]])))[:,1]
predict4

array([0.00796465], dtype=float32)

In [25]:
from tensorflow.keras.models import load_model


In [26]:
cust_model = load_model('customer_behavior_model/1/')

In [27]:
 prediction3 = cust_model.predict(sc.transform(np.array([[42,50000]])))[:,1]
 prediction3

array([0.64286834], dtype=float32)

In [28]:
predict4 = model.predict(sc.transform(np.array([[20,40000]])))[:,1]
predict4

array([0.00796465], dtype=float32)

In [29]:
!zip -r customermodel.zip customer_behavior_model  

  adding: customer_behavior_model/ (stored 0%)
  adding: customer_behavior_model/1/ (stored 0%)
  adding: customer_behavior_model/1/variables/ (stored 0%)
  adding: customer_behavior_model/1/variables/variables.data-00000-of-00001 (deflated 55%)
  adding: customer_behavior_model/1/variables/variables.index (deflated 64%)
  adding: customer_behavior_model/1/saved_model.pb (deflated 88%)
  adding: customer_behavior_model/1/assets/ (stored 0%)


In [30]:
from google.colab import files

In [31]:
!ls

customer_behavior_model  customermodel.zip  sample_data


In [33]:
files.download('customermodel.zip')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>