In [3]:
import numpy as np

In [4]:
import pickle

In [5]:
!ls


sample_data


In [11]:
!wget https://github.com/futurexskill/ml-model-deployment/raw/main/classifier.pickle

--2020-10-12 18:04:58--  https://github.com/futurexskill/ml-model-deployment/raw/main/classifier.pickle
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/futurexskill/ml-model-deployment/main/classifier.pickle [following]
--2020-10-12 18:04:58--  https://raw.githubusercontent.com/futurexskill/ml-model-deployment/main/classifier.pickle
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2113 (2.1K) [application/octet-stream]
Saving to: ‘classifier.pickle’

classifier.pickle   100%[===================>]   2.06K  --.-KB/s    in 0s      

2020-10-12 18:04:58 (35.9 MB/s) - ‘classifier.pickle’ saved [2113/2113]


In [12]:
!ls

classifier.pickle  sample_data


In [13]:
!wget https://github.com/futurexskill/ml-model-deployment/raw/main/sc.pickle

--2020-10-12 18:05:34--  https://github.com/futurexskill/ml-model-deployment/raw/main/sc.pickle
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/futurexskill/ml-model-deployment/main/sc.pickle [following]
--2020-10-12 18:05:34--  https://raw.githubusercontent.com/futurexskill/ml-model-deployment/main/sc.pickle
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 502 [application/octet-stream]
Saving to: ‘sc.pickle’

sc.pickle           100%[===================>]     502  --.-KB/s    in 0s      

2020-10-12 18:05:34 (21.3 MB/s) - ‘sc.pickle’ saved [502/502]



In [14]:
!ls

classifier.pickle  sample_data	sc.pickle


In [16]:
classifier_colab = pickle.load(open('classifier.pickle','rb'))


/usr/local/lib/python3.6/dist-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator KNeighborsClassifier from version 0.23.1 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [17]:
scaler_colab = pickle.load(open('sc.pickle','rb'))

/usr/local/lib/python3.6/dist-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator StandardScaler from version 0.23.1 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [18]:
new_pred = classifier_colab.predict(scaler_colab.transform(np.array([[40,20000]])))


In [19]:
new_pred

array([0])

In [21]:
new_pred_proba = classifier_colab.predict_proba(scaler_colab.transform(np.array([[40,20000]])))[:,1]
new_pred_proba


array([0.2])

In [24]:
new_pred_2 = classifier_colab.predict(scaler_colab.transform(np.array([[42,50000]])))
new_pred_proba_2 = classifier_colab.predict_proba(scaler_colab.transform(np.array([[42,50000]])))[:,1]
new_pred_2

array([1])

In [25]:
new_pred_proba_2

array([0.8])