In [1]:
!python --version

Python 3.6.9


In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'2.3.0'

Tensorflow has two data types - Tensor and Variable


In [4]:
tf.constant(10)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [6]:
tf_const = tf.constant([10,20])

In [8]:
tf_const

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>

In [10]:
tf_const.numpy()

array([10, 20], dtype=int32)

In [12]:
var1 = tf_const.numpy()
var1

array([10, 20], dtype=int32)

In [14]:
tensor1 = tf.convert_to_tensor(var1)

In [15]:
tensor1

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>

In [19]:
x_2d_tensor = tf.constant([[10,20,30],[40,50,60]])
x_2d_tensor 

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 20, 30],
       [40, 50, 60]], dtype=int32)>

In [22]:
x_zero_tensor = tf.zeros([3,4])
x_zero_tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [24]:
x_ones_tensor = tf.ones([2,3])
x_ones_tensor


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [25]:
x_2d_tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 20, 30],
       [40, 50, 60]], dtype=int32)>

In [26]:
tf.reshape(x_2d_tensor,[3,2])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40],
       [50, 60]], dtype=int32)>

Variable - can be modified


In [27]:
tf_var = tf.Variable([[10,20,30],[40,50,60]])

In [28]:
tf_var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[10, 20, 30],
       [40, 50, 60]], dtype=int32)>

In [29]:
tf_var.assign([[100,200,300],[400,500,600]])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[100, 200, 300],
       [400, 500, 600]], dtype=int32)>

In [30]:
tf_var[1,2].assign(0)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[100, 200, 300],
       [400, 500,   0]], dtype=int32)>

In [31]:
tf_var.assign_add([[10,20,300],[4,50,60]])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[110, 220, 600],
       [404, 550,  60]], dtype=int32)>